swagger: '2.0'
info:
  title: The Game API
  description: Web services for The Game
  version: 0.1.0
produces:
  - application/json
paths:
  /v1/ping:
    get:
      operationId: ping
      summary: Returns pong.
      x-google-backend:
        address: https://us-central1-the-game-388502.cloudfunctions.net/the-game-ping
      responses:
        '200':
          description: Just pong.
          schema:
            type: string
security:
  - firebase: []
securityDefinitions:
  firebase:
    authorizationUrl: ''
    flow: 'implicit'
    type: 'oauth2'
    # Replace YOUR-PROJECT-ID with your project ID
    x-google-issuer: 'https://securetoken.google.com/the-game-388502'
    x-google-jwks_uri: 'https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com'
    x-google-audiences: 'the-game-388502'
