openapi: 3.0.0
info:
  title: The Game API
  description: Web services for The Game
  version: 0.1.9
paths:
  /v1/ping:
    get:
      summary: Returns pong.
      x-google-backend:
        address: https://us-central1-the-game-388502.cloudfunctions.net/the-game-ping
      responses:
        '200': # status code
          description: Just pong.
          content:
            application/json:
              schema:
                type: string
