name: 'Deploy client'

on:
  workflow_dispatch:
  push:
    paths:
      - projects/client/**/*
      - .github/workflows/deploy-client.yml
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  deploy_client:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./projects/client
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '18'

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('package-lock.json') }}
      #     restore-keys: npm-

      # - name: npm install
      #   run: npm install

      # - name: npm build
      #   run: npm run build

      # - name: Export next app
      #   run: npx next export

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'

      # - name: Install pipenv
      #   run: |
      #     python -m pip install --upgrade pipenv wheel

      # - id: cache-pipenv
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      # - name: Install Pythton dependencies
      #   run: |
      #     cd ${{ github.workspace }}
      #     pipenv install --deploy --dev

      # - name: Enforce Deployment Folder Index
      #   run: |
      #     pipenv run python ${{ github.workspace }}/bin/edfi ./out --ci

      - name: GCP auth
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Gcloud auth list
        run: gcloud auth list

      - name: Set GCP Docker auth
        run: gcloud auth configure-docker

      - name: Print Docker config
        run: cat ~/.docker/config.json

      - name: Build Docker image
        run: docker build -t the-game-client .

      - name: Tag Docker image
        run: docker tag the-game-client us-central1-docker.pkg.dev/the-game-388502/the-game-docker/client:latest

      - name: Push Docker image to GCP
        run: docker push us-central1-docker.pkg.dev/the-game-388502/the-game-docker/client

      # - name: Upload react app
      #   run: |
      #     gsutil -m -o GSUtil:parallel_composite_upload_threshold=150M cp -r out/* \
      #     gs://the-game.kevinmccartney.dev/
